Update rules.yml

diff --git a/.github/workflows/rules.yml b/.github/workflows/rules.yml
--- a/.github/workflows/rules.yml
+++ b/.github/workflows/rules.yml
@@ -42,11 +42,11 @@ jobs:
                 "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Reject/Malicious.list"
                 "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Reject/Tracking.list"
             )
-            > Tool-repo/Ruleset/Domain_reject.list
+            > Tool-repo/Ruleset/Ad_Blocking.list
             for url in "${urls[@]}"; do
                 echo "Downloading: $url"
-                curl -f -L "$url" >> Tool-repo/Ruleset/Domain_reject.list || { echo "Download Failed: $url"; exit 1; }
-                echo "" >> Tool-repo/Ruleset/Domain_reject.list
+                curl -f -L "$url" >> Tool-repo/Ruleset/Ad_Blocking.list || { echo "Download Failed: $url"; exit 1; }
+                echo "" >> Tool-repo/Ruleset/Ad_Blocking.list
             done
             # 合并全球域名规则
             urls=(
@@ -58,11 +58,11 @@ jobs:
                 "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/gfw.txt"
                 "https://raw.githubusercontent.com/Repcz/Tool/refs/heads/X/Surge/Rules/DownloadCDN_Global.list"
             )
-            > Tool-repo/Ruleset/Domain_Final.list
+            > Tool-repo/Ruleset/Global.list
             for url in "${urls[@]}"; do
                 echo "Downloading: $url"
-                curl -f -L "$url" >> Tool-repo/Ruleset/Domain_Final.list || { echo "Download Failed: $url"; exit 1; }
-                echo "" >> Tool-repo/Ruleset/Domain_Final.list
+                curl -f -L "$url" >> Tool-repo/Ruleset/Global.list || { echo "Download Failed: $url"; exit 1; }
+                echo "" >> Tool-repo/Ruleset/Global.list
             done
             # 合并苹果域名规则
             urls=(
@@ -72,11 +72,11 @@ jobs:
                 "https://ruleset.skk.moe/List/non_ip/apple_cn.conf"
                 "https://ruleset.skk.moe/List/non_ip/apple_cdn.conf"
             )
-            > Tool-repo/Ruleset/Domain_Apple.list
+            > Tool-repo/Ruleset/Apple.list
             for url in "${urls[@]}"; do
                 echo "Downloading: $url"
-                curl -f -L "$url" >> Tool-repo/Ruleset/Domain_Apple.list || { echo "Download Failed: $url"; exit 1; }
-                echo "" >> Tool-repo/Ruleset/Domain_Apple.list
+                curl -f -L "$url" >> Tool-repo/Ruleset/Apple.list || { echo "Download Failed: $url"; exit 1; }
+                echo "" >> Tool-repo/Ruleset/Apple.list
             done
             # 合并斗鱼/Direct-fix/DownloadCDN_CN规则
             urls=(
@@ -84,11 +84,11 @@ jobs:
                 "https://raw.githubusercontent.com/iTiaodahai/Tool/refs/heads/main/Surge/Rules/Direct.list"
                 "https://raw.githubusercontent.com/Repcz/Tool/refs/heads/X/Surge/Rules/DownloadCDN_CN.list"
             )
-            > Tool-repo/Ruleset/Domain_CN.list
+            > Tool-repo/Ruleset/Direct_CN.list
             for url in "${urls[@]}"; do
                 echo "Downloading: $url"
-                curl -f -L "$url" >> Tool-repo/Ruleset/Domain_CN.list || { echo "Download Failed: $url"; exit 1; }
-                echo "" >> Tool-repo/Ruleset/Domain_CN.list
+                curl -f -L "$url" >> Tool-repo/Ruleset/Direct_CN.list || { echo "Download Failed: $url"; exit 1; }
+                echo "" >> Tool-repo/Ruleset/Direct_CN.list
             done            
             # 合并Microsoft/PayPal/Talkatone/Google规则
             urls=(
@@ -99,11 +99,11 @@ jobs:
                 "https://raw.githubusercontent.com/Repcz/Tool/X/Surge/Custom/Talkatone.list"
                 "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list"
             )
-            > Tool-repo/Ruleset/Domain_US.list
+            > Tool-repo/Ruleset/Proxy_US.list
             for url in "${urls[@]}"; do
                 echo "Downloading: $url"
-                curl -f -L "$url" >> Tool-repo/Ruleset/Domain_US.list || { echo "Download Failed: $url"; exit 1; }
-                echo "" >> Tool-repo/Ruleset/Domain_US.list
+                curl -f -L "$url" >> Tool-repo/Ruleset/Proxy_US.list || { echo "Download Failed: $url"; exit 1; }
+                echo "" >> Tool-repo/Ruleset/Proxy_US.list
             done
             # 合并GitHub/YouTube/Reddit/TikTok规则
             urls=(
@@ -112,11 +112,11 @@ jobs:
                 "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Surge/Reddit/Reddit.list"
                 "https://raw.githubusercontent.com/Repcz/Tool/refs/heads/X/Surge/Rules/TikTok.list"
             )
-            > Tool-repo/Ruleset/Global_any.list
+            > Tool-repo/Ruleset/Proxy_any.list
             for url in "${urls[@]}"; do
                 echo "Downloading: $url"
-                curl -f -L "$url" >> Tool-repo/Ruleset/Global_any.list || { echo "Download Failed: $url"; exit 1; }
-                echo "" >> Tool-repo/Ruleset/Global_any.list
+                curl -f -L "$url" >> Tool-repo/Ruleset/Proxy_any.list || { echo "Download Failed: $url"; exit 1; }
+                echo "" >> Tool-repo/Ruleset/Proxy_any.list
             done
             # 合并Facebook/Instagram/WhatsApp/Twitter/Wikipedia/Spotify规则
             urls=(
@@ -127,11 +127,11 @@ jobs:
                 "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Surge/Wikipedia/Wikipedia.list"
                 "https://raw.githubusercontent.com/iTiaodahai/Tool/refs/heads/main/Surge/Rules/Spotify.list"              
             )
-            > Tool-repo/Ruleset/Domain_JP.list
+            > Tool-repo/Ruleset/Proxy_Social.list
             for url in "${urls[@]}"; do
                 echo "Downloading: $url"
-                curl -f -L "$url" >> Tool-repo/Ruleset/Domain_JP.list || { echo "Download Failed: $url"; exit 1; }
-                echo "" >> Tool-repo/Ruleset/Domain_JP.list
+                curl -f -L "$url" >> Tool-repo/Ruleset/Proxy_Social.list || { echo "Download Failed: $url"; exit 1; }
+                echo "" >> Tool-repo/Ruleset/Proxy_Social.list
             done
             # 合并Telegram规则
             urls=(
@@ -151,11 +151,11 @@ jobs:
                 "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.list"
                 "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrimeVideo/PrimeVideo.list"
             )
-            > Tool-repo/Ruleset/US_Stream.list
+            > Tool-repo/Ruleset/Proxy_Stream.list
             for url in "${urls[@]}"; do
                 echo "Downloading: $url"
-                curl -f -L "$url" >> Tool-repo/Ruleset/US_Stream.list || { echo "Download Failed: $url"; exit 1; }
-                echo "" >> Tool-repo/Ruleset/US_Stream.list
+                curl -f -L "$url" >> Tool-repo/Ruleset/Proxy_Stream.list || { echo "Download Failed: $url"; exit 1; }
+                echo "" >> Tool-repo/Ruleset/Proxy_Stream.list
             done
             # 合并AI规则
             urls=(
